#!/bin/bash

#parameters are <threshold> <visitors.....>

for name in ${@:2}; do
	echo $name
	for file in `ls`; do
		if [[ -d $file ]]; then
			points=( `./room_challenges ${file} ${1} | grep -w $name | cut -d" " -f2-3` )
			visit_check=`cat ${file}/visitors.txt | grep -w ${name}`
			
			if [[ ${points[1]} == "" && ${points[2]} == "" ]]; then
				if [[ ${visit_check} == "" ]]; then
					continue
				else
					points[1]=0
					points[2]=0
				fi
			fi

			if [[ ${points[1]} == "" ]]; then
				points[1]=0
			fi
			
			if [[ ${points[2]} == "" ]]; then
				points[2]=0
			fi
			
			echo -e '\t'${file}: ${points[1]} ${points[2]}
		fi
	done
done


