#!/bin/bash

#params (room_name, threshold)
#This function take room name and threshold for input, and output the neccesery data. each visitor that took challenges with amount of wins and loses.
#This function output all the necesery data not ordered!
function all_data_not_ordered {

	all_names=( `cut -d" " -f3 ${1}/visitors.txt | sort | uniq` )
	
	for x in ${all_names[*]}; do
		winners=( `./visitor_challenges ${1} $x ${2} | cut -d" " -f2 | grep Winner | uniq -c` )
		loser=( `./visitor_challenges ${1} $x ${2} | cut -d" " -f2 | grep Loser | uniq -c` )
	
		if [[ ${winners[0]} == "" && ${loser[0]} == "" ]]; then
			continue
		fi	

		if [[ ${winners[0]} == "" ]]; then
			winners[0]=0
		fi
		
		if [[ ${loser[0]} == "" ]]; then
			loser[0]=0
		fi

		summer=$(( ${winners[0]} + ${loser[0]} ))
		echo ${x} ${winners[0]} ${loser[0]} ${summer}	
	done
}

all_data_not_ordered ${1} ${2} | sort | sort -srk4 | cut -d" " -f1-3

