#!/bin/bash

#function that take parameter (room_name, visitor_id,threshold) and output 
function files {
	for file in `ls ${1}/challenges`; do
		if [[ $file==[*].chg  ]]; then
			visit_id_challenge=`grep visit ${1}/challenges/$file | cut -d" " -f3`
			if [[ ${visit_id_challenge} == ${2} ]]; then
				overall=`grep overall ${1}/challenges/$file | cut -d" " -f3`
				if [[ ${overall} < ${3} ]]; then
					echo ${2} Winner
				else
					echo ${2} Loser
				fi
			fi
		fi
	done
}

#funcion that take (room_name, visitor_name, threshold), find all the visits if of the visitor_name and use files function
function take_all_visits {
	for id in `grep -w ${2} ${1}/visitors.txt | cut -d" " -f2`; do
		files ${1} $id ${3}
	done
}

take_all_visits ${1} ${2} ${3} | sort -n



